apiVersion: v1
kind: Service
metadata:
  name: {{ include "src-website.fullname" . }}
  labels:
    {{- include "src-website.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: 8080
  selector:
    {{- include "src-website.selectorLabels" . | nindent 4 }}
